# Generated by Django 2.1.5 on 2024-03-26 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0003_auto_20240320_1133'),
        ('rango', '0002_auto_20240320_0900'),
    ]

    operations = [
    ]
